name: Yard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Check documentation completion
        run: |
          completion_percentage=$(bundle exec yard | tee /dev/stdout  | tail -1 | cut -d'%' -f1 | xargs)
          echo $completion_percentage
          if [[ $completion_percentage != "100.00" ]]; then
            echo "YARD documentation must be at 100%"
            exit 2;
          fi
