name: Yard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Check documentation completion
        run: |
          completion_percentage=$(bundle exec yard | tee /dev/stdout  | tail -1 | cut -d'%' -f1 | bc)
          echo $completion_percentage
          if [ $completion_percentage != '100.00' ]; then
            echo "YARD documentation must be at 100%"
            exit 2;
          fi